events {
    worker_connections 1024;
}

stream {
    upstream nacos_http {
        server nacos-1:8848;
        server nacos-2:8848;
        server nacos-3:8848;
    }

    upstream nacos_grpc {
        server nacos-1:9848;
        server nacos-2:9848;
        server nacos-3:9848;
    }

    server {
        listen 8848;
        proxy_pass nacos_http;
    }

    server {
        listen 9848;
        proxy_pass nacos_grpc;
    }
}
