brokerClusterName=MvpRocketMqCluster
brokerName=broker-b
brokerId=0
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

namesrvAddr=rocketmq-namesrv-1:9876;rocketmq-namesrv-2:9876
brokerIP1=host.docker.internal
listenPort=10921
haListenPort=10922

autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
deleteWhen=04
fileReservedTime=48

storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
