spring:
  cloud:
    gateway:
      routes:
        # 路由说明：
        # 1. predicates 先根据请求路径判断是否命中路由；
        # 2. uri 使用 lb://服务名，表示通过 Spring Cloud LoadBalancer 从 Nacos 选择服务实例；
        # 3. 命中路由后转发到对应下游服务。

        # 用户服务路由
        - id: service-user-route # 路由唯一标识
          uri: lb://service-user-0 # 通过 Nacos 服务名进行负载均衡转发
          predicates:
            - Path=/user/** # 匹配用户接口

        # 菜单服务路由
        - id: service-menu-route # 侧边栏菜单接口由 service-user-0 提供
          uri: lb://service-user-0
          predicates:
            - Path=/menu/** # 匹配菜单接口

        # 鉴权接口路由
        - id: service-auth-route # 注册、登录、刷新、登出暂时都由 service-user-0 提供
          uri: lb://service-user-0
          predicates:
            - Path=/auth/**

        # 秒杀商品服务路由
        - id: service-goods-route # 秒杀商品配置管理接口
          uri: lb://service-goods-0
          predicates:
            - Path=/goods/**

        # 秒杀订单服务路由
        - id: service-order-route # 秒杀下单和结果查询接口
          uri: lb://service-order-0
          predicates:
            - Path=/order/**
